wsl = false
no-multigrid = false
vsync = true
maximized = false
srgb = true
idle = true
frame = "full"
title-hidden = true

[font]
# normal = ["Monaspace Neon"]
# italic = ["Monaspace Radon"]
# bold = [{ family = "Monaspace Neon", style = "Bold" }]
# bold_italic = [{ family = "Monaspace Radon", style = "Bold" }]
normal = ["RecMonoDuotone Nerd Font Mono"]
# italic = ["RecMonoDuotone Nerd Font"]
# bold = ["RecMonoDuotone Nerd Font"]
# bold_italic = ["RecMonoDuotone Nerd Font"]
size = 14.0

[font.features]
"RecMonoDuotoneNF" = [
  "dlig",
  "ss01",
  "ss02",
  "ss07",
  "ss08",
  "+calt",
  "+liga"
]
"RecMonoDuotone Nerd Font" = [
  "dlig",
  "ss01",
  "ss02",
  "ss07",
  "ss08",
  "+calt",
  "+liga"
]
"Monaspace Neon" = [
  "+liga",
  "+calt",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08",
  "+ss09",
  "+cv01 2",
  "+cv11",
  "+cv31",
]
"Monaspace Radon" = [
  "+liga",
  "+calt",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08",
  "+ss09",
  "+cv01 2",
  "+cv11",
  "+cv31",
]
"Monaspace Neon Bold" = [
  "+liga",
  "+calt",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08",
  "+ss09",
  "+cv01 2",
  "+cv11",
  "+cv31",
]
"Monaspace Radon Bold" = [
  "+liga",
  "+calt",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08",
  "+ss09",
  "+cv01 2",
  "+cv11",
  "+cv31",
]
