wsl = false
no-multigrid = false
vsync = true
maximized = false
srgb = true
idle = true
frame = "full"
title-hidden = true

[font]
normal = ["MonaspiceNe Nerd Font"]
size = 13.0

[font.features]
"MonaspiceNe Nerd Font" = [
  "+liga",
  "+calt",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08",
  "+ss09",
]
