return {
  { -- further customize the options set by the community
    "catppuccin",
    opts = {
      flavour = "macchiato",
      integrations = {
        sandwich = true,
        alpha = true,
        noice = true,
        mini = true,
        leap = true,
        markdown = true,
        neotest = true,
        cmp = true,
        overseer = true,
        lsp_trouble = true,
        rainbow_delimiters = true,
        neotree = true,
        gitsigns = true,
        which_key = true,
        telescope = { enabled = true },
        treesitter = true,
        notify = true,
        indent_blankline = { enabled = true },
        ufo = true,
        window_picker = true,
        copilot_vim = true,
        dashboard = true,
      },
    },
  },
}
