#!/bin/bash

# TODO: Maybe rename the variables and functions to something
# referencing the fact that these are only foreground/text colors

# Declarations

## Colors

### 8 Base colors
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)

### Extended colors
PURPLE=$(tput setaf 125)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)

## Styles
BRIGHT=$(tput bold)
# Below seemed to be causing issues on endeavouros
# BLINK=$(tput blink)
# REVERSE=$(tput smso)
# UNDERLINE=$(tput smul)
BOLD=$(tput bold)
## Reset
NORMAL=$(tput sgr0)

# Formatting functions

## Colors
black() {
	printf "%s" "${BLACK}${*}${NORMAL}"
}

blue() {
	printf "%s" "${BLUE}${*}${NORMAL}"
}

red() {
	printf "%s" "${RED}${*}${NORMAL}"
}

yellow() {
	printf "%s" "${YELLOW}${*}${NORMAL}"
}

green() {
	printf "%s" "${GREEN}${*}${NORMAL}"
}

white() {
	printf "%s" "${WHITE}${*}${NORMAL}"
}

## Styles
bold() {
	printf "%s" "${BOLD}${*}${NORMAL}"
}

# Exports

## Colors
export BLACK RED GREEN YELLOW LIME_YELLOW POWDER_BLUE MAGENTA CYAN WHITE BLUE PURPLE
## Styles
export BRIGHT BLINK REVERSE UNDERLINE NORMAL
