#!/bin/bash
# Package lists for supported package managers
rpm_packages=(
	zsh
	git
	cmake
	openssh
	tree
	lsd
	bat
	tldr
	gh
	trash-cli
	brightnessctl
	playerctl
	pactl
	neovim
	ranger
	kitty
	alacritty
	luarocks
	atool
	highlight
	shellcheck
	shfmt
	python
	golang
	bc
	python3-pylint-venv
	pipx
	"https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
	"https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
	pkg-config
	openssl-devel
)

rpm_groups=(
	c-development
	development-tools
	python-science
)

arch_packages=(
	yay
	base-devel
	zsh
	git
	openssh
	sheldon
	tree
	lsd
	bat
	tldr
	github-cli
	trash-cli
	brightnessctl
	playerctl
	# pactl
	neovim
	ranger
	kitty
	wezterm
	alacritty
	luarocks
	atool
	ueberzug
	highlight
	shellcheck
	shfmt
	python
	go
	bc
	openssl
	pkg-config
  pipx
  python3-venv
)

cargo_packages=(
	fd-find
	ripgrep
	sheldon
	cargo-update
)

export rpm_packages rpm_groups arch_packages cargo_packages
