#!/bin/bash
# Package lists for supported package managers
rpm_packages=(
	zsh
	git
	cmake
	openssh
	tree
	lsd
	bat
	tldr
	gh
	trash-cli
	brightnessctl
	playerctl
	pactl
	neovim
	ranger
	kitty
	alacritty
	luarocks
	atool
	highlight
	shellcheck
	shfmt
	python
	golang
	bc
	pipx
	pkg-config
	openssl-devel
)

rpm_nonfree=(
	"https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
	"https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
)

apt_packages=(
	zsh
	git
	cmake
	openssh-client
	tree
	lsd
	bat
	tldr
	gh
	trash-cli
	brightnessctl
	playerctl
	pulseaudio-utils
	ranger
	kitty
	alacritty
	luarocks
	atool
	highlight
	shellcheck
	shfmt
	python
	golang
	bc
	pipx
	pkg-config
	libssl-dev
)

rpm_groups=(
	c-development
	development-tools
	python-science
)

arch_packages=(
	yay
	base-devel
	zsh
	git
	openssh
	sheldon
	tree
	lsd
	bat
	tldr
	github-cli
	trash-cli
	brightnessctl
	playerctl
	# pactl
	neovim
	ranger
	kitty
	wezterm
	alacritty
	luarocks
	atool
	ueberzug
	highlight
	shellcheck
	shfmt
	python
	go
	bc
	openssl
	pkg-config
	pipx
)

cargo_packages=(
	fd-find
	ripgrep
	sheldon
	cargo-update
)

pipx_packages=(
	black
	jrnl
	pynvim
	pylint
	pyllint-venv
	isort
)

npm_packages=(
	commitizen
	npkill
	fkill-cli
	cz-conventional-changelog
)

export rpm_packages rpm_groups rpm_nonfree arch_packages cargo_packages pipx_packages apt_packages npm_packages
