#!/bin/bash
# Utility functions for use in other scripts

_exists() {
	command -v "$1" >/dev/null 2>&1
}

# Informational messages
info() {
	printf "%s\n" "${CYAN}${*}${NORMAL}"
}

# Success reporter
success() {
	printf "%s\n" "${GREEN}${BOLD}${*}${NORMAL}"
}

# Error reporter
error() {
	printf "%s\n" "${RED}${BOLD}${*}${NORMAL}"
}

# Warning or otherwise important message
warn() {
	printf "%s\n" "${YELLOW}${*}${NORMAL}"
}

# End section
finish() {
	success "Done!"
	printf "%s\n" ""
	sleep 1
}

export _exists info success error warn finish
