#!/bin/bash
# Utility functions for use in other scripts

source "${DOTFILES}/scripts/fg_colors"

_exists() {
	command -v "$1" >/dev/null 2>&1
}

# Informational messages
info() {
	printf "%s\n" "${CYAN}${*}${NORMAL}"
}

# Success reporter
success() {
	printf "%s\n" "${GREEN}${BOLD}${*}${NORMAL}"
}

# Error reporter
error() {
	printf "%s\n" "${RED}${BOLD}${*}${NORMAL}"
}

# Warning or otherwise important message
warn() {
	printf "%s\n" "${YELLOW}${*}${NORMAL}"
}

# End section
finish() {
	success "Done!"
	echo
	sleep 1
}

on_finish() {
	echo
	success "Setup was successfully done!"
	success "Happy Coding!"
}

on_error() {
	echo
	error "ERROR"
	error "${*}"
	echo
	exit 1
}

find_package_manager() {
	local manager=""
	if _exists dnf; then
		manager="rpm"
	fi
	if _exists pacman; then
		manager="arch"
	fi
	# if _exists apt; then
	# 	manager="apt"
	# fi

	if [[ -n "${manager}" ]]; then
		printf %s "${manager}"
	else
		warn "No supported package manager found."
		on_error "Unable to continue."
	fi
}

_current_shell() {
	printf %s "$(readlink /proc/$$/exe | sed "s/.*\///")"
}

_user_default_shell() {
	printf %s "$(awk -F: -v user="$(whoami)" '$1 == user {print $NF}' /etc/passwd | rev | cut -d"/" -f1 | rev)"
}
