[plugins]

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.alias-tips]
github = 'djui/alias-tips'
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"
apply = ["defer"]

[plugins.auto-notify]
github = "marzocchi/zsh-notify"
apply = ["defer"]

[plugins.z]
github = "agkozak/zsh-z"
apply = ["defer"]

[plugins.lib]
local = "~/.dotfiles/lib"

[templates]
# defer = "{% for file in files %} zsh-defer source \"{{ file }}\"\n{% endfor %}"
defer = '''
  {% for file in files %}
    zsh-defer source "{{ file }}"
  {% endfor %}
'''
